# Development

livereload: true
port: 8000
open_url: true
strict_front_matter: true

# Site

timezone: America/New_York
url: https://katsute.dev

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - /dependencies/node/bootstrap/scss
  - /node_modules
  - /CNAME
  - /LICENSE
  - /README.md

  - /src
  - /build*
  - /dist
  - /package*.json
  - /tsconfig.json

sass:
  load_paths:
    - dependencies/katsute/css
    - dependencies/node/bootstrap/scss
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []